application: brink-commerce
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

handlers:

- url: /(.+)
  static_files: dist/\1
  upload: dist/(.*)
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"

- url: /
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  http_headers:
    Vary: Accept-Encoding
    Strict-Transport-Security: "max-age=2592000; includeSubdomains"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?